Project_PRN221_SonVN/Final_Project_HE153101/Models/Schedule.cs
using System;
using System.Collections.Generic;

namespace Final_Project_HE153101.Models
{
    public partial class Schedule
    {
        public Schedule()
        {
            ScheduleDetails = new HashSet<ScheduleDetail>();
        }

        public int ScheduleId { get; set; }
        public string ScheduleName { get; set; } = null!;
        public int TeacherId { get; set; }
        public int RoomId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }

        public virtual Class Class { get; set; } = null!;
        public virtual Room Room { get; set; } = null!;
        public virtual Subject Subject { get; set; } = null!;
        public virtual Teacher Teacher { get; set; } = null!;
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_HE153101.Models; 
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System.Text.Json;

namespace Final_Project_HE153101.Pages.Schedules
{
    public class AddModel : PageModel
    {
        private readonly fapfptContext _context; 

        public AddModel(fapfptContext context)
        {
            _context = context;
        }
     
        [BindProperty]
        public Schedule Schedule { get; set; }

        public List<Class> Classes { get; set; }
        public List<Subject> Subjects { get; set; }
        public List<Teacher> Teachers { get; set; }
        public List<Room> Rooms { get; set; }
        public List<Slot> TimeSlots { get; set; }
        [BindProperty]
        public int SelectedTimeSlotId { get; set; }

        public int ScheduleId { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
        public async Task OnGetAsync()
        {
            Classes = await _context.Classes.ToListAsync();
            Subjects = await _context.Subjects.ToListAsync();
            Teachers = await _context.Teachers.ToListAsync();
            Rooms = await _context.Rooms.ToListAsync();
            TimeSlots = await _context.Slots.ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Schedules.Add(Schedule);
            await _context.SaveChangesAsync();

            var newScheduleDetail = new ScheduleDetail
            {
                ScheduleId = Schedule.ScheduleId,
                SlotId = SelectedTimeSlotId,
                                         
            };

            _context.ScheduleDetails.Add(newScheduleDetail);
            await _context.SaveChangesAsync();

            return RedirectToPage("./view");
        }


    }
}

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_HE153101.Models;
using System.Threading.Tasks;
using System.Linq;

namespace Final_Project_HE153101.Pages.Schedules
{
    public class EditModel : PageModel
    {
        private readonly fapfptContext _context;

        public EditModel(fapfptContext context)
        {
            _context = context;
            TimeSlots = new List<Slot>();
        }

        [BindProperty]
        public Schedule Schedule { get; set; }

        [BindProperty]
        public int SelectedSlotId { get; set; }
      


    
        public IList<Class> Classes { get; set; }
        public IList<Subject> Subjects { get; set; }
        public IList<Teacher> Teachers { get; set; }
        public IList<Room> Rooms { get; set; }
        public IList<Slot> TimeSlots { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Schedule = await _context.Schedules
                .Include(s => s.ScheduleDetails)
                .FirstOrDefaultAsync(m => m.ScheduleId == id);

            if (Schedule == null)
            {
                return NotFound();
            }

            SelectedSlotId = Schedule.ScheduleDetails.FirstOrDefault()?.SlotId ?? 0;

            Classes = await _context.Classes.ToListAsync();
            Subjects = await _context.Subjects.ToListAsync();
            Teachers = await _context.Teachers.ToListAsync();
            Rooms = await _context.Rooms.ToListAsync();
            TimeSlots = await _context.Slots.ToListAsync();

            if (Schedule == null)
            {
                return NotFound();
            }
            return Page();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Schedule).State = EntityState.Modified;

           
            var scheduleDetail = await _context.ScheduleDetails
                .FirstOrDefaultAsync(sd => sd.ScheduleId == Schedule.ScheduleId);

            if (scheduleDetail != null)
            {
                scheduleDetail.SlotId = SelectedSlotId; 
                _context.Attach(scheduleDetail).State = EntityState.Modified;
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Schedules.Any(e => e.ScheduleId == Schedule.ScheduleId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./view");
        }


    }
}

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/LoadFile.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Final_Project_HE153101.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Final_Project_HE153101.Pages.Schedules
{
    public class LoadFileModel : PageModel
    {
        private readonly fapfptContext _context;

        public LoadFileModel(fapfptContext context)
        {
            _context = context;
        }

        [BindProperty]
        public IFormFile Upload { get; set; }
        public class ScheduleInputModel
        {
            public string RoomName { get; set; }
            public string CourseCode { get; set; }
            public string ClassName { get; set; }
            public string TeacherName { get; set; }
            public string TimeslotTypeName { get; set; }
        }
        public List<ScheduleInputModel> SchedulesFromJson { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (Upload != null && Upload.Length > 0)
            {
                using (var reader = new StreamReader(Upload.OpenReadStream()))
                {
                    var fileContent = await reader.ReadToEndAsync();
                    var schedules = JsonConvert.DeserializeObject<List<ScheduleInputModel>>(fileContent);
                    SchedulesFromJson = JsonConvert.DeserializeObject<List<ScheduleInputModel>>(fileContent);


                    //foreach (var scheduleInput in schedules)
                    //{
                      
                    //    var room = await _context.Rooms.FirstOrDefaultAsync(r => r.RoomName == scheduleInput.RoomName);
                    //    if (room == null)
                    //    {
                            
                    //        room = new Room { RoomName = scheduleInput.RoomName };
                    //        _context.Rooms.Add(room);
                    //        await _context.SaveChangesAsync();
                    //    }

                      
                    //    var newSchedule = new Schedule
                    //    {
                        
                    //        RoomId = room.RoomId,
                          
                    //    };

                    //    _context.Schedules.Add(newSchedule);
                    //    await _context.SaveChangesAsync();

                     
                    //    var slot = await _context.Slots.FirstOrDefaultAsync(s => s.SlotName == scheduleInput.TimeslotTypeName);
                    //    if (slot != null)
                    //    {
                    //        var newScheduleDetail = new ScheduleDetail
                    //        {
                    //            ScheduleId = newSchedule.ScheduleId,
                    //            SlotId = slot.SlotId
                    //        };

                    //        _context.ScheduleDetails.Add(newScheduleDetail);
                    //        await _context.SaveChangesAsync();
                    //    }
                    //}

                }
                return Page();
            }
       
            ModelState.AddModelError(string.Empty, "Please upload a file.");
            return Page();
        }
    }
}

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/View.cshtml.cs
using Final_Project_HE153101.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Final_Project_HE153101.Pages.Schedules
{
    public class ViewModel : PageModel
    {
        private readonly fapfptContext _context;

        public ViewModel(fapfptContext context)
        {
            _context = context;
        }
        public string ClassFilter { get; set; }
        public string SubjectFilter { get; set; }
        public string TeacherFilter { get; set; }
        public string RoomFilter { get; set; }
        public string TimeSlotFilter { get; set; }
        public IList<Schedule> Schedules { get; set; } = default!;

        public IList<Class> Classes { get; set; } = new List<Class>();
        public IList<Subject> Subjects { get; set; } = new List<Subject>();
        public IList<Teacher> Teachers { get; set; } = new List<Teacher>();
        public IList<Room> Rooms { get; set; } = new List<Room>();
        public IList<Slot> TimeSlots { get; set; } = new List<Slot>();

        public int PageIndex { get; set; }
        public int TotalPages { get; set; }

        public bool HasPreviousPage => PageIndex > 1;
        public bool HasNextPage => PageIndex < TotalPages;

        public int PageSize { get; } = 4; 


        public async Task OnGetAsync(string classFilter, string subjectFilter, string teacherFilter,
            string roomFilter, int? timeSlotFilter, int pageIndex = 1)
        {
          
            ClassFilter = classFilter;
            SubjectFilter = subjectFilter;
            TeacherFilter = teacherFilter;
            RoomFilter = roomFilter;

            Classes = await _context.Classes.ToListAsync();
            Subjects = await _context.Subjects.ToListAsync();
            Teachers = await _context.Teachers.ToListAsync();
            Rooms = await _context.Rooms.ToListAsync();
            TimeSlots = await _context.Slots.ToListAsync();

            var query = _context.Schedules.AsQueryable();

            if (!string.IsNullOrEmpty(ClassFilter))
            {
                query = query.Where(s => s.Class.ClassName.Contains(ClassFilter));
            }
            if (!string.IsNullOrEmpty(SubjectFilter))
            {
                query = query.Where(s => s.Subject.SubjectName.Contains(SubjectFilter));
            }
            if (!string.IsNullOrEmpty(TeacherFilter))
            {
                query = query.Where(s => s.Teacher.TeacherName.Contains(TeacherFilter));
            }
            if (!string.IsNullOrEmpty(RoomFilter))
            {
                query = query.Where(s => s.Room.RoomName.Contains(RoomFilter));
            }
            int? timeSlotFilterId = null;
            if (int.TryParse(TimeSlotFilter, out var parsedId))
            {
                timeSlotFilterId = parsedId;
            }

            
            if (timeSlotFilterId.HasValue)
            {
                query = query.Where(s => s.ScheduleDetails.Any(sd => sd.SlotId == timeSlotFilterId.Value));
            }

            var totalItems = await query.CountAsync();
            TotalPages = (int)Math.Ceiling(totalItems / (double)PageSize);

            PageIndex = pageIndex;

            Schedules = await query
                .Skip((PageIndex - 1) * PageSize)
                .Take(PageSize)
                .Include(s => s.Class)
                .Include(s => s.Subject)
                .Include(s => s.Teacher)
                .Include(s => s.Room)
                .Include(s => s.ScheduleDetails).ThenInclude(sd => sd.Slot)
                .ToListAsync();

        }
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            try
            {
                var scheduledetail = _context.ScheduleDetails.Where(od => od.ScheduleId == id).ToList();

                if (scheduledetail.Any())
                {
                    _context.ScheduleDetails.RemoveRange(scheduledetail);
                    await _context.SaveChangesAsync();
                }

                var schedule = await _context.Schedules.FindAsync(id);
                if (schedule != null)
                {
                    _context.Schedules.Remove(schedule);
                    await _context.SaveChangesAsync();
                }
            }
            catch (Exception ex)
            {

                System.Diagnostics.Debug.WriteLine("Error deleting schedule: " + ex.Message);

            }

            return RedirectToPage();
        }

    }
}

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/Add.cshtml
@page
@model Final_Project_HE153101.Pages.Schedules.AddModel

<h2>Add Schedule</h2>
 
<form method="post" enctype="multipart/form-data">
    <select asp-for="Schedule.ClassId" asp-items="@(new SelectList(Model.Classes, "ClassId", "ClassName"))">
        <option value="">Select Class</option>
    </select>

    <select asp-for="Schedule.SubjectId" asp-items="@(new SelectList(Model.Subjects, "SubjectId", "SubjectName"))">
        <option value="">Select Subject</option>
    </select>

    <select asp-for="Schedule.TeacherId" asp-items="@(new SelectList(Model.Teachers, "TeacherId", "TeacherName"))">
        <option value="">Select Teacher</option>
    </select>

    <select asp-for="Schedule.RoomId" asp-items="@(new SelectList(Model.Rooms, "RoomId", "RoomName"))">
        <option value="">Select Room</option>
    </select>


    <select asp-for="SelectedTimeSlotId" asp-items="@(new SelectList(Model.TimeSlots, "SlotId", "SlotName"))">
        <option value="">Select Time Slot</option>
    </select>

    <button type="submit">Add Schedule</button>
</form>
<a href="./LoadFile" class="btn btn-secondary">Load Data from JSON</a>

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/Edit.cshtml
@page
@model Final_Project_HE153101.Pages.Schedules.EditModel
@using Final_Project_HE153101.Models


<h2>Edit Schedule</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Schedule.ClassId">Class</label>
        <select asp-for="Schedule.ClassId" class="form-control">
            @if (Model.Classes != null)
            {
                @foreach (var cls in Model.Classes)
                {
                    <option value="@cls.ClassId">@cls.ClassName</option>
                }
            }

        </select>
    </div>

    <div class="form-group">
        <label asp-for="Schedule.SubjectId">Subject</label>
        <select asp-for="Schedule.SubjectId" class="form-control">
            @if (Model.Subjects != null)
            {
                @foreach (var subject in Model.Subjects)
                {
                    <option value="@subject.SubjectId">@subject.SubjectName</option>
                }
            }
           
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Schedule.TeacherId">Teacher</label>
        <select asp-for="Schedule.TeacherId" class="form-control">
              @if (Model.Teachers != null)
            {
                @foreach (var teacher in Model.Teachers)
                {
                    <option value="@teacher.TeacherId">@teacher.TeacherName</option>
                }
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Schedule.RoomId">Room</label>
        <select asp-for="Schedule.RoomId" class="form-control">
              @if (Model.Rooms != null)
            {
                @foreach (var room in Model.Rooms)
                {
                    <option value="@room.RoomId">@room.RoomName</option>
                }
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="SelectedSlotId">Time Slot</label>
        <select asp-for="SelectedSlotId" class="form-control" asp-items="@(Model.TimeSlots != null ? new SelectList(Model.TimeSlots, "SlotId", "SlotName") : new SelectList(Enumerable.Empty<Slot>()))">

            <option value="">Select Time Slot</option>
        </select>
    </div>



    <button type="submit" class="btn btn-primary">Save changes</button>
</form>

<a href="./view">Back to List</a>

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/LoadFile.cshtml
@page
@model Final_Project_HE153101.Pages.Schedules.LoadFileModel

<h2>Load Schedule from JSON File</h2>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="upload">Upload JSON File:</label>
        <input type="file" id="upload" name="upload" />
    </div>
    <button type="submit" class="btn btn-primary">Upload and Process</button>
</form>


@if (Model.SchedulesFromJson != null && Model.SchedulesFromJson.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>Class</th>
                <th>Subject</th>
                <th>Teacher</th>
                <th>Room</th>
                <th>Time Slot</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.SchedulesFromJson)
            {
                <tr>
                    <td>@item.ClassName</td>
                    <td>@item.CourseCode</td>
                    <td>@item.TeacherName</td>
                    <td>@item.RoomName</td>
                    <td>@item.TimeslotTypeName</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No data loaded from JSON file.</p>
}

Project_PRN221_SonVN/Final_Project_HE153101/Pages/Schedules/View.cshtml
@page
@model Final_Project_HE153101.Pages.Schedules.ViewModel
@using Final_Project_HE153101.Models
<link rel="stylesheet" href="~/css/site.css" />



<h2>Schedules</h2>

<div class="filter-bar">
  <form method="get">

          <select name="classFilter" >
            <option value="">All Classes</option>
            @foreach (var cls in Model.Classes)
            {         
                    <option value="@cls.ClassId">@cls.ClassName</option>
            }
        </select>

        <select name="subjectFilter">
            <option value="">All Subjects</option>
            @foreach (var subject in Model.Subjects)
            {
                <option value="@subject.SubjectId">@subject.SubjectName</option>
            }
        </select>

        <select name="teacherFilter">
            <option value="">All Teachers</option>
            @foreach (var teacher in Model.Teachers)
            {
                <option value="@teacher.TeacherId">@teacher.TeacherName</option>
            }
        </select>

        <select name="roomFilter">
            <option value="">All Rooms</option>
            @foreach (var room in Model.Rooms)
            {
                <option value="@room.RoomId">@room.RoomName</option>
            }
        </select>

        <select name="timeSlotFilter">
            <option value="">All Time Slots</option>
            @foreach (var timeSlot in Model.TimeSlots)
            {
                <option value="@timeSlot.SlotId">@timeSlot.SlotName</option>
            }
        </select>
    <button type="submit">Filter</button>
</form>
</div>
<a class="btn-add" href="/Schedules/Add">Input New Schedule</a>


<table class="custom-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Class</th>
            <th>Subject</th>
            <th>Teacher</th>
            <th>Room</th>
            <th>Time Slot</th> 
           
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Schedules)
        {
            <tr>
                <td>@item.ScheduleId</td>
                <td>@item.Class.ClassName</td>
                <td>@item.Subject.SubjectName</td>
                <td>@item.Teacher.TeacherName</td>
                <td>@item.Room.RoomName</td>               
                <td>
                    @foreach (var detail in item.ScheduleDetails)
                    {
                        <div>@detail.Slot.SlotName</div>
                        <div>@detail.Slot.StartSlot.ToString("HH:mm") - @detail.Slot.EndSlot.ToString("HH:mm")</div>
                    }
                </td>
                <td>
                    <a class="btn btn-primary" asp-page="/Schedules/edit" asp-route-id="@item.ScheduleId">Edit</a>
                </td>
                <td>
                   
                    <form method="post" asp-page-handler="Delete" asp-route-id="@item.ScheduleId" style="display:inline;">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?');">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
@if (TempData["Message"] != null)
{
    <div class="alert alert-success">@TempData["Message"]</div>
}


@if (Model.TotalPages > 1)
{
    <nav>
        <ul class="pagination">
            <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                <a class="page-link" asp-page="./View" asp-route-pageIndex="@(Model.PageIndex - 1)">Previous</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                    <a class="page-link" asp-page="./View" asp-route-pageIndex="@i">@i</a>
                </li>
            }
            <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                <a class="page-link" asp-page="./View" asp-route-pageIndex="@(Model.PageIndex + 1)">Next</a>
            </li>
        </ul>
    </nav>
}